name: Linting

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: "18.x" # Garante o uso do Node 18 idêntico ao seu

      - name: Instalar dependências de forma limpa
        run: npm ci

      - name: Executar testes com Jest
        run: npm run lint:prettier:check
